/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

/**
 *
 * @author Dell
 */
public class QuanLyThongKeUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyThongKeUI
     */
    public QuanLyThongKeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThongKeBanHang = new javax.swing.JButton();
        btnThongKeDoanhThu = new javax.swing.JButton();
        btnQuanLyNganSach = new javax.swing.JButton();

        btnThongKeBanHang.setBackground(new java.awt.Color(0, 204, 255));
        btnThongKeBanHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThongKeBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKeBanHang.setText("Thống kê bán hàng");
        btnThongKeBanHang.setBorderPainted(false);
        btnThongKeBanHang.setFocusPainted(false);

        btnThongKeDoanhThu.setBackground(new java.awt.Color(0, 204, 255));
        btnThongKeDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThongKeDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKeDoanhThu.setText("Thống kê doanh thu");
        btnThongKeDoanhThu.setBorderPainted(false);
        btnThongKeDoanhThu.setFocusPainted(false);

        btnQuanLyNganSach.setBackground(new java.awt.Color(0, 204, 255));
        btnQuanLyNganSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQuanLyNganSach.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyNganSach.setText("Quản lý ngân sách");
        btnQuanLyNganSach.setBorderPainted(false);
        btnQuanLyNganSach.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThongKeDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKeBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyNganSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnThongKeBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyNganSach, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuanLyNganSach;
    private javax.swing.JButton btnThongKeBanHang;
    private javax.swing.JButton btnThongKeDoanhThu;
    // End of variables declaration//GEN-END:variables
}
