/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import GiaoDien.ChiTietSanPhamUI;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import static support.SupportUIClass.createNewJFrame;

/**
 *
 * @author Dell
 */
public class QuanLySanPhamUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySanPhamUI
     */
    private DanhSachSanPhamUI danhSachSanPhamUI;
    private ChiTietSanPhamUI chiTietSanPhamUI;
    
    public QuanLySanPhamUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemSanPham = new javax.swing.JButton();
        btnDanhSachSanPham = new javax.swing.JButton();

        btnThemSanPham.setBackground(new java.awt.Color(0, 204, 255));
        btnThemSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSanPham.setText("Thêm sản phẩm");
        btnThemSanPham.setToolTipText("");
        btnThemSanPham.setBorderPainted(false);
        btnThemSanPham.setFocusPainted(false);
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        btnDanhSachSanPham.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachSanPham.setText("Danh sách sản phẩm");
        btnDanhSachSanPham.setToolTipText("");
        btnDanhSachSanPham.setBorderPainted(false);
        btnDanhSachSanPham.setFocusPainted(false);
        btnDanhSachSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhSachSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDanhSachSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
       
        
    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        // TODO add your handling code here:
        chiTietSanPhamUI = new  ChiTietSanPhamUI();
        createNewJFrame(chiTietSanPhamUI, "Nhập đơn đặt hàng");
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void btnDanhSachSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachSanPhamActionPerformed
        // TODO add your handling code here:
         danhSachSanPhamUI = new DanhSachSanPhamUI();
         createNewJFrame(danhSachSanPhamUI, "Nhập đơn đặt hàng");
    }//GEN-LAST:event_btnDanhSachSanPhamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachSanPham;
    private javax.swing.JButton btnThemSanPham;
    // End of variables declaration//GEN-END:variables
}
