/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import GiaoDien.ChiTietHoaDonBanHangUI;
import java.awt.Dimension;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.WindowConstants;
import static support.SupportUIClass.createNewJFrame;

/**
 *
 * @author Dell
 */
public class QuanLyBanHangUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyBanHangUI
     */
    
    private ChiTietHoaDonBanHangUI banHangUI;
    private DanhSachHoaDonBanHangUI danhSachHoaDonUI;
   
    
    public QuanLyBanHangUI() {
        initComponents();
    }

    public ChiTietHoaDonBanHangUI getBanHangUI() {
        return banHangUI;
    }

    public void setBanHangUI(ChiTietHoaDonBanHangUI banHangUI) {
        this.banHangUI = banHangUI;
    }

    public DanhSachHoaDonBanHangUI getDanhSachHoaDonUI() {
        return danhSachHoaDonUI;
    }

    public void setDanhSachHoaDonUI(DanhSachHoaDonBanHangUI danhSachHoaDonUI) {
        this.danhSachHoaDonUI = danhSachHoaDonUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLapHoaDonBanHang = new javax.swing.JButton();
        btnDanhSachHoaDon = new javax.swing.JButton();

        btnLapHoaDonBanHang.setBackground(new java.awt.Color(0, 204, 255));
        btnLapHoaDonBanHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLapHoaDonBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnLapHoaDonBanHang.setText("Lập hóa đơn bán hàng");
        btnLapHoaDonBanHang.setToolTipText("");
        btnLapHoaDonBanHang.setBorderPainted(false);
        btnLapHoaDonBanHang.setFocusPainted(false);
        btnLapHoaDonBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHoaDonBanHangActionPerformed(evt);
            }
        });

        btnDanhSachHoaDon.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachHoaDon.setText("Danh sách hóa đơn bán hàng");
        btnDanhSachHoaDon.setToolTipText("");
        btnDanhSachHoaDon.setBorderPainted(false);
        btnDanhSachHoaDon.setFocusPainted(false);
        btnDanhSachHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLapHoaDonBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhSachHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLapHoaDonBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDanhSachHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapHoaDonBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHoaDonBanHangActionPerformed
        // TODO add your handling code here:
        banHangUI = new ChiTietHoaDonBanHangUI();
        createNewJFrame(banHangUI, "Lập hóa đơn bán hàng");
      
    }//GEN-LAST:event_btnLapHoaDonBanHangActionPerformed

    private void btnDanhSachHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachHoaDonActionPerformed
        // TODO add your handling code here:
        danhSachHoaDonUI = new DanhSachHoaDonBanHangUI();
        createNewJFrame(danhSachHoaDonUI, "Danh sách hóa đơn");
        
    }//GEN-LAST:event_btnDanhSachHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachHoaDon;
    private javax.swing.JButton btnLapHoaDonBanHang;
    // End of variables declaration//GEN-END:variables
}
