/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import GiaoDien.ChiTietHoaDonDatHangUI;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import static support.SupportUIClass.createNewJFrame;

/**
 *
 * @author Dell
 */
public class QuanLyMuaHangUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyMuaHang
     */
    
    private ChiTietHoaDonDatHangUI chiTietHoaDonDatHangUI;
    private ChiTietHoaDonNhapHangUI chiTietHoaDonNhapHangUI;
    private DanhSachDonDatHangUI danhSachDonDatHangUI;
    private DanhSachDonNhapHangUI danhSachDonNhapHangUI;
    
    
    public QuanLyMuaHangUI() {
        initComponents();
        chiTietHoaDonDatHangUI = new  ChiTietHoaDonDatHangUI();
        chiTietHoaDonNhapHangUI = new ChiTietHoaDonNhapHangUI();
        danhSachDonDatHangUI = new DanhSachDonDatHangUI();
        danhSachDonNhapHangUI = new DanhSachDonNhapHangUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDanhSachDonNhapHang = new javax.swing.JButton();
        btnNhapDonNhapHang = new javax.swing.JButton();
        btnDanhSachDonDatHang = new javax.swing.JButton();
        btnLapDonDatHang = new javax.swing.JButton();

        btnDanhSachDonNhapHang.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachDonNhapHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachDonNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachDonNhapHang.setText("Dánh Sách đơn nhập hàng");
        btnDanhSachDonNhapHang.setToolTipText("");
        btnDanhSachDonNhapHang.setBorderPainted(false);
        btnDanhSachDonNhapHang.setFocusPainted(false);
        btnDanhSachDonNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachDonNhapHangActionPerformed(evt);
            }
        });

        btnNhapDonNhapHang.setBackground(new java.awt.Color(0, 204, 255));
        btnNhapDonNhapHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNhapDonNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapDonNhapHang.setText("Nhập đơn nhập hàng");
        btnNhapDonNhapHang.setToolTipText("");
        btnNhapDonNhapHang.setBorderPainted(false);
        btnNhapDonNhapHang.setFocusPainted(false);
        btnNhapDonNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDonNhapHangActionPerformed(evt);
            }
        });

        btnDanhSachDonDatHang.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachDonDatHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachDonDatHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachDonDatHang.setText("Dánh Sách đơn đặt hàng");
        btnDanhSachDonDatHang.setToolTipText("");
        btnDanhSachDonDatHang.setBorderPainted(false);
        btnDanhSachDonDatHang.setFocusPainted(false);
        btnDanhSachDonDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachDonDatHangActionPerformed(evt);
            }
        });

        btnLapDonDatHang.setBackground(new java.awt.Color(0, 204, 255));
        btnLapDonDatHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLapDonDatHang.setForeground(new java.awt.Color(255, 255, 255));
        btnLapDonDatHang.setText("Lập đơn đặt hàng");
        btnLapDonDatHang.setToolTipText("");
        btnLapDonDatHang.setBorderPainted(false);
        btnLapDonDatHang.setFocusPainted(false);
        btnLapDonDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapDonDatHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLapDonDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnDanhSachDonDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDanhSachDonNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapDonNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLapDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapDonNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDanhSachDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhSachDonNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhSachDonNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachDonNhapHangActionPerformed
        // TODO add your handling code here:
        createNewJFrame(danhSachDonNhapHangUI, "Danh sách đơn nhập hàng");
    }//GEN-LAST:event_btnDanhSachDonNhapHangActionPerformed

    private void btnNhapDonNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDonNhapHangActionPerformed
        // TODO add your handling code here:
         createNewJFrame(chiTietHoaDonNhapHangUI, "Nhập đơn nhập hàng");
    }//GEN-LAST:event_btnNhapDonNhapHangActionPerformed

    private void btnDanhSachDonDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachDonDatHangActionPerformed
        // TODO add your handling code here:
         createNewJFrame(danhSachDonDatHangUI, "Danh sách đơn đặt hàng");
    }//GEN-LAST:event_btnDanhSachDonDatHangActionPerformed

    private void btnLapDonDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapDonDatHangActionPerformed
        // TODO add your handling code here:
         createNewJFrame(chiTietHoaDonDatHangUI, "Lập đơn đặt hàng");
    }//GEN-LAST:event_btnLapDonDatHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachDonDatHang;
    private javax.swing.JButton btnDanhSachDonNhapHang;
    private javax.swing.JButton btnLapDonDatHang;
    private javax.swing.JButton btnNhapDonNhapHang;
    // End of variables declaration//GEN-END:variables
}
