/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import GiaoDien.DanhSachNhanVienUI;
import GiaoDien.ChiTietNhanVienUI;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import static support.SupportUIClass.createNewJFrame;

/**
 *
 * @author Dell
 */
public class QuanLyNhanVienUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyBanHangUI
     */
    
    
   private DanhSachNhanVienUI danhSachNhanVienUI;
   private ChiTietNhanVienUI chiTietNhanVienUI;
   
    public QuanLyNhanVienUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDanhSachNhanVien = new javax.swing.JButton();
        btnThemNhanVien = new javax.swing.JButton();

        btnDanhSachNhanVien.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachNhanVien.setText("Danh sách nhân viên");
        btnDanhSachNhanVien.setBorderPainted(false);
        btnDanhSachNhanVien.setFocusPainted(false);
        btnDanhSachNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachNhanVienActionPerformed(evt);
            }
        });

        btnThemNhanVien.setBackground(new java.awt.Color(0, 204, 255));
        btnThemNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhanVien.setText("Thêm nhân viên");
        btnThemNhanVien.setBorderPainted(false);
        btnThemNhanVien.setFocusPainted(false);
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDanhSachNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDanhSachNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        // TODO add your handling code here:
        danhSachNhanVienUI = new DanhSachNhanVienUI();
        createNewJFrame(chiTietNhanVienUI, "Thêm nhân viên");
    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void btnDanhSachNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachNhanVienActionPerformed
        // TODO add your handling code here:
        chiTietNhanVienUI = new ChiTietNhanVienUI();
        createNewJFrame(danhSachNhanVienUI, "Danh sách nhân viên");
    }//GEN-LAST:event_btnDanhSachNhanVienActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachNhanVien;
    private javax.swing.JButton btnThemNhanVien;
    // End of variables declaration//GEN-END:variables
}
