/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanmoi;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Point;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Dell
 */
public class ChucNangChinhUI extends javax.swing.JPanel {

    /**
     * Creates new form mainUI
     */
    
    private QuanLyKhachHangUI quanLyKhachHangUI;
    private QuanLyNhanVienUI quanLyNhanVienUI;
    private QuanLyThuChi quanLyThuChi;
    private QuanLyThongKeUI quanLyThongKeUI;
    private QuanLyMuaHang quanLyMuaHang;
    private QuanLyBanHangUI quanLyBanHangUI;
    private QuanLySanPhamUI quanLySanPhamUI;
    public ChiTietNhaCungCap chiTietNhaCungCap;
    
    
    
    
    public ChucNangChinhUI() {
        initComponent();
        initComponents(); 
        addControls();
        addEvents();
    }

    private void initComponent()
    {
        quanLyKhachHangUI = new QuanLyKhachHangUI();
        quanLyNhanVienUI = new QuanLyNhanVienUI();
        quanLyThongKeUI = new QuanLyThongKeUI();
        quanLyThuChi = new QuanLyThuChi();
        quanLySanPhamUI = new QuanLySanPhamUI();
        quanLyBanHangUI = new QuanLyBanHangUI();
        quanLyMuaHang = new QuanLyMuaHang();
        chiTietNhaCungCap = new ChiTietNhaCungCap();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        btnBanHang1 = new javax.swing.JButton();
        btnMuaHang1 = new javax.swing.JButton();
        btnSanPham1 = new javax.swing.JButton();
        btnNhanVien1 = new javax.swing.JButton();
        btnBaoCao1 = new javax.swing.JButton();
        btnKhachHang1 = new javax.swing.JButton();
        btnThuChi1 = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBanHang1.setBackground(new java.awt.Color(0, 153, 204));
        btnBanHang1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBanHang1.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\sale.png")); // NOI18N
        btnBanHang1.setText("Quản lý bán hàng");
        btnBanHang1.setBorder(null);
        btnBanHang1.setBorderPainted(false);
        btnBanHang1.setFocusPainted(false);
        btnBanHang1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnBanHang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanHang1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBanHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHang1ActionPerformed(evt);
            }
        });

        btnMuaHang1.setBackground(new java.awt.Color(153, 0, 153));
        btnMuaHang1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMuaHang1.setForeground(new java.awt.Color(255, 255, 255));
        btnMuaHang1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\buy.png")); // NOI18N
        btnMuaHang1.setText("Quản lý mua hàng");
        btnMuaHang1.setBorder(null);
        btnMuaHang1.setBorderPainted(false);
        btnMuaHang1.setFocusPainted(false);
        btnMuaHang1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMuaHang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMuaHang1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMuaHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaHang1ActionPerformed(evt);
            }
        });

        btnSanPham1.setBackground(new java.awt.Color(51, 102, 0));
        btnSanPham1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSanPham1.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\base.png")); // NOI18N
        btnSanPham1.setText("Quản lý sản phẩm");
        btnSanPham1.setBorder(null);
        btnSanPham1.setBorderPainted(false);
        btnSanPham1.setFocusPainted(false);
        btnSanPham1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSanPham1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanPham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPham1ActionPerformed(evt);
            }
        });

        btnNhanVien1.setBackground(new java.awt.Color(0, 153, 255));
        btnNhanVien1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNhanVien1.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\staff.png")); // NOI18N
        btnNhanVien1.setText("Quản lý nhân viên");
        btnNhanVien1.setBorder(null);
        btnNhanVien1.setBorderPainted(false);
        btnNhanVien1.setFocusPainted(false);
        btnNhanVien1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnNhanVien1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVien1ActionPerformed(evt);
            }
        });

        btnBaoCao1.setBackground(new java.awt.Color(0, 102, 51));
        btnBaoCao1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBaoCao1.setForeground(new java.awt.Color(255, 255, 255));
        btnBaoCao1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\report2.png")); // NOI18N
        btnBaoCao1.setText("Quản lý báo cáo");
        btnBaoCao1.setBorder(null);
        btnBaoCao1.setBorderPainted(false);
        btnBaoCao1.setFocusPainted(false);
        btnBaoCao1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnBaoCao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaoCao1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBaoCao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCao1ActionPerformed(evt);
            }
        });

        btnKhachHang1.setBackground(new java.awt.Color(153, 0, 51));
        btnKhachHang1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKhachHang1.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\custemer.png")); // NOI18N
        btnKhachHang1.setText("Khách hàng");
        btnKhachHang1.setBorder(null);
        btnKhachHang1.setBorderPainted(false);
        btnKhachHang1.setFocusPainted(false);
        btnKhachHang1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnKhachHang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHang1ActionPerformed(evt);
            }
        });

        btnThuChi1.setBackground(new java.awt.Color(255, 102, 0));
        btnThuChi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThuChi1.setForeground(new java.awt.Color(255, 255, 255));
        btnThuChi1.setIcon(new javax.swing.ImageIcon("D:\\Nhap mon cong nghe phan mem\\DoAnNhapMonCongNghePhanMem\\images\\casher.png")); // NOI18N
        btnThuChi1.setText("Quản lý thu chi");
        btnThuChi1.setBorder(null);
        btnThuChi1.setBorderPainted(false);
        btnThuChi1.setFocusPainted(false);
        btnThuChi1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnThuChi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThuChi1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThuChi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuChi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThuChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMuaHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBaoCao1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBanHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMuaHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnSanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThuChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBaoCao1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 194, Short.MAX_VALUE)
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(697, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHang1ActionPerformed
        // TODO add your handling code here:
       
       pnRight.removeAll();
       pnRight.add(quanLyBanHangUI);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
     
    
    }//GEN-LAST:event_btnBanHang1ActionPerformed

    private void btnMuaHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaHang1ActionPerformed
        // TODO add your handling code here:
       pnRight.removeAll();
       pnRight.add(quanLyMuaHang);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
    }//GEN-LAST:event_btnMuaHang1ActionPerformed

    private void btnSanPham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPham1ActionPerformed
        // TODO add your handling code here:
       pnRight.removeAll();
       pnRight.add(quanLySanPhamUI);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
    }//GEN-LAST:event_btnSanPham1ActionPerformed

    private void btnNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVien1ActionPerformed
        // TODO add your handling code here:
       pnRight.removeAll();
       pnRight.add(quanLyNhanVienUI);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
    }//GEN-LAST:event_btnNhanVien1ActionPerformed

    private void btnBaoCao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCao1ActionPerformed
        // TODO add your handling code here:
       pnRight.removeAll();
       pnRight.add(quanLyThongKeUI);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
    }//GEN-LAST:event_btnBaoCao1ActionPerformed

    private void btnKhachHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHang1ActionPerformed
        // TODO add your handling code here:
       pnRight.removeAll();
       pnRight.add(quanLyKhachHangUI);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
    }//GEN-LAST:event_btnKhachHang1ActionPerformed

    private void btnThuChi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuChi1ActionPerformed
        // TODO add your handling code here:
       pnRight.removeAll();
       pnRight.add(quanLyThuChi);
       pnRight.setLayout(new GridLayout());
       pnRight.revalidate(); 
       pnRight.repaint();
    }//GEN-LAST:event_btnThuChi1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang1;
    private javax.swing.JButton btnBaoCao1;
    private javax.swing.JButton btnKhachHang1;
    private javax.swing.JButton btnMuaHang1;
    private javax.swing.JButton btnNhanVien1;
    private javax.swing.JButton btnSanPham1;
    private javax.swing.JButton btnThuChi1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnRight;
    // End of variables declaration//GEN-END:variables

    private void addControls() {
       
         pnRight.setPreferredSize(new Dimension(1150,680));
    }

    private void addEvents() {
  
    }
}
