/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanmoi;

/**
 *
 * @author Dell
 */
public class QuanLyKhachHangUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKhachHangUI
     */
    public QuanLyKhachHangUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDanhSachNhaCungCap = new javax.swing.JButton();
        btnDanhSachKhachHang = new javax.swing.JButton();

        btnDanhSachNhaCungCap.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachNhaCungCap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachNhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachNhaCungCap.setText("Danh sách nhà cung câp");
        btnDanhSachNhaCungCap.setToolTipText("");
        btnDanhSachNhaCungCap.setBorderPainted(false);
        btnDanhSachNhaCungCap.setFocusPainted(false);
        btnDanhSachNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachNhaCungCapActionPerformed(evt);
            }
        });

        btnDanhSachKhachHang.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachKhachHang.setText("Danh sách khách hàng");
        btnDanhSachKhachHang.setToolTipText("");
        btnDanhSachKhachHang.setBorderPainted(false);
        btnDanhSachKhachHang.setFocusPainted(false);
        btnDanhSachKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDanhSachKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhSachNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDanhSachKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDanhSachNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhSachNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhSachNhaCungCapActionPerformed

    private void btnDanhSachKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhSachKhachHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachKhachHang;
    private javax.swing.JButton btnDanhSachNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
