/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanmoi;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Dell
 */
public class QuanLyMuaHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyMuaHang
     */
    
    private DatHangUI datHangUI;
    
    public QuanLyMuaHang() {
        initComponents();
        datHangUI = new  DatHangUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDanhSachNhapHang = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnDanhSachDatHang = new javax.swing.JButton();
        btnDatHang = new javax.swing.JButton();

        btnDanhSachNhapHang.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachNhapHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachNhapHang.setText("Dánh Sách đơn nhập hàng");
        btnDanhSachNhapHang.setToolTipText("");
        btnDanhSachNhapHang.setBorderPainted(false);
        btnDanhSachNhapHang.setFocusPainted(false);
        btnDanhSachNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachNhapHangActionPerformed(evt);
            }
        });

        btnNhapHang.setBackground(new java.awt.Color(0, 204, 255));
        btnNhapHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHang.setText("Nhập đơn nhập hàng");
        btnNhapHang.setToolTipText("");
        btnNhapHang.setBorderPainted(false);
        btnNhapHang.setFocusPainted(false);
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnDanhSachDatHang.setBackground(new java.awt.Color(0, 204, 255));
        btnDanhSachDatHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDanhSachDatHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachDatHang.setText("Dánh Sách đơn đặt hàng");
        btnDanhSachDatHang.setToolTipText("");
        btnDanhSachDatHang.setBorderPainted(false);
        btnDanhSachDatHang.setFocusPainted(false);
        btnDanhSachDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachDatHangActionPerformed(evt);
            }
        });

        btnDatHang.setBackground(new java.awt.Color(0, 204, 255));
        btnDatHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDatHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDatHang.setText("Lập đơn đặt hàng");
        btnDatHang.setToolTipText("");
        btnDatHang.setBorderPainted(false);
        btnDatHang.setFocusPainted(false);
        btnDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnDanhSachDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDanhSachNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDanhSachDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhSachNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhSachNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachNhapHangActionPerformed
        // TODO add your handling code here:
        JFrame jfrBanHang = new JFrame("Lập phiếu đặt hàng");
        jfrBanHang.getContentPane();
        jfrBanHang.add(datHangUI);
        jfrBanHang.setSize(datHangUI.getPreferredSize());
        jfrBanHang.setLocationRelativeTo(null);
        jfrBanHang.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jfrBanHang.setVisible(true);
    }//GEN-LAST:event_btnDanhSachNhapHangActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnDanhSachDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachDatHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhSachDatHangActionPerformed

    private void btnDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSachDatHang;
    private javax.swing.JButton btnDanhSachNhapHang;
    private javax.swing.JButton btnDatHang;
    private javax.swing.JButton btnNhapHang;
    // End of variables declaration//GEN-END:variables
}
